<a href="https://colab.research.google.com/github/NeerajRijhwani/MachineLearningBasics/blob/main/numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy-Introduction

###Creating Matrix

In [1]:
import numpy as np
arr=np.array([[12,87,45,33],
[90,14,62,77],
[8,59,26,41],
[73,11,95,64],
[50,38,70,29]])
print("The Matrix is \n",arr,"\n")

The Matrix is 
 [[12 87 45 33]
 [90 14 62 77]
 [ 8 59 26 41]
 [73 11 95 64]
 [50 38 70 29]] 



###Creating Transpose Of The Matrix

In [2]:
transposeArr=np.transpose(arr)
print("The Transpose of Matrix is \n",transposeArr,"\n")

The Transpose of Matrix is 
 [[12 90  8 73 50]
 [87 14 59 11 38]
 [45 62 26 95 70]
 [33 77 41 64 29]] 



###Dot Product Of Matrix

In [3]:
dotproduct=np.dot(arr,transposeArr)
print("The Dot Product Of Matrix With Its Transpose is\n",dotproduct,"\n")

The Dot Product Of Matrix With Its Transpose is
 [[10827  7629  7752  8220  8013]
 [ 7629 18069  6315 17542 11605]
 [ 7752  6315  5902  6327  5651]
 [ 8220 17542  6327 18571 12574]
 [ 8013 11605  5651 12574  9685]] 



###Mean Of Each Column

In [4]:
columnwisemean=np.mean(transposeArr,axis=0)
print("The columnwise mean : ",columnwisemean,"\n")

The columnwise mean :  [44.25 60.75 33.5  60.75 46.75] 



###Standard Deviation Of Each Row

In [5]:
rowwisestandarddev=np.std(transposeArr,axis=1)
print("The rowwise standard deviation : ",rowwisestandarddev)

The rowwise standard deviation :  [32.4936917  28.54750427 23.27745691 18.59462288]
